version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    assignees:
      - "joaquinbejar"
    labels:
      - "deps"
    groups:
      cargo-minor-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    assignees:
      - "joaquinbejar"
    labels:
      - "deps"
    groups:
      gha-minor-patch:
        update-types:
          - "minor"
          - "patch"
